FormBuilder/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'FormBuilder.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

formbuilder/urls.py
from django.conf.urls import patterns, url

from formbuilder import views

urlpatterns = patterns(
    '',
    url(r'^$', views.index, name='index'),
    url(r'^login$', views.login, name='login'),
    url(r'^builder$', views.builder, name='builder'),
    url(r'^get_form_templates$', views.get_form_templates,
        name='get_form_templates'),
)

urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns(
    '',
    url(r'^formbuilder/',
        include('formbuilder.urls', namespace="formbuilder")),
    url(r'',
        include('formbuilder.urls', namespace="formbuilder")),
    url(r'^admin/', include(admin.site.urls)),
)

formbuilder/models.py
from django.db import models

# Create your models here.

formbuilder/views.py
import json
from django.conf import settings
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from snaplib.api2.api import Api
from .view_decorators import (require_authentication,)


@require_authentication
def index(request):
    """
    Display catalog with available forms
    :param request: incoming request
    :type request: HttpRequest
    :return: response
    :rtype: HttpResponse
    """
    return render(request, 'catalog.html')


def login(request):
    """
    Handles login actions (display login form, handle passed data)
    :param request: incoming request
    :type request: HttpRequest
    :return: response
    :rtype: HttpResponse
    """
    request.session.flush()
    if request.POST:
        api = Api(settings.SNAP_API_BASE_URL, settings.SNAP_INITIAL_PRINCIPAL)
        response = api.authenticate(
            username=request.POST['username'],
            password=request.POST['password'],
        )
        if response.status_code >= 400:
            return render(
                request,
                'login.html',
                {'error_message': response.json()['message']}
            )
        request.session['user'] = response.json()['user']
        request.session['profile'] = response.json()['userProfile']
        # request.session['api'] = api
        return HttpResponseRedirect(reverse('formbuilder:index'))

    return render(request, 'login.html')


@require_authentication
def get_form_templates(request):
    """
    returns json with templates
    :param request: incoming request
    :type request: HttpRequest
    :return: response
    :rtype: HttpResponse
    """
    api = Api(settings.SNAP_API_BASE_URL, settings.SNAP_INITIAL_PRINCIPAL)
    templates_collection = api['/formTemplates']
    templates = []
    for template in list(templates_collection.collection_items()):
        t = {
            'name': template['formTemplate']['data']['name'],
            'revisionNumber': template[
                'formTemplate']['data']['revisionNumber'],
            'status': template['formTemplate']['data']['status'],
            'uuid': template['formTemplate']['metadata']['uuid']
        }
        templates.insert(0, t)
    return HttpResponse(json.dumps(templates))


@require_authentication
def builder(request):
    """
    Display form Builder 
    :param request: incoming request
    :type request: HttpRequest
    :return: response
    :rtype: HttpResponse
    """
    return render(request, 'builder.html')

formbuilder/templates/builder.html
<h1>Balanga</h1>>

formbuilder/templates/catalog.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Forms Catalog 0</title>

    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'formbuilder/css/style.css' %}" />

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Forms Catalog</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <span class="navbar-form navbar-right">
            <div class="form-group">
            	
              <input type="text" placeholder="search" id="search" name="search" class="form-control">
            </div>
          </span>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <div id="magic-table">
        	<div id="loading"></div>
        </div>
      </div>
    </div>

    <div class="container">
      <footer>
        <p>&copy; Seamless Medical Systems 2014</p>
      </footer>
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'MagicTable/js/tableData.js' %}"></script>
    <script src="{% static 'MagicTable/js/jquery-ui.js' %}"></script>
    <script src="{% static 'MagicTable/js/magicTable-0.1.js' %}"></script>
    <script src="{% static 'formbuilder/js/main.js' %}"></script>
  </body>
</html>

formbuilder/templates/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Form Log in 0</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'formbuilder/css/signin.css' %}" />

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="container">

      <form class="form-signin" action="{% url 'formbuilder:login' %}" method="post">
        {% csrf_token %}
        <h2 class="form-signin-heading">Please sign in</h2>
        {% if error_message %}
            <p class="text-danger bg-danger">{{ error_message }}</p>
        {% endif %}
        <label for="username" class="sr-only">Username:</label>
        <input type="text" id="username" name="username" class="form-control" placeholder="Username" required autofocus>
        <label for="password" class="sr-only">Password</label>
        <input type="password" id="password" name="password" class="form-control" placeholder="Password" required>
        
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      </form>

    </div> <!-- /container -->


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
  </body>
</html>